// Catalog data for the "itil" pack: plain data, no React. Shared by the pack (rendering) and the MCP server.
// Do not import UI code here (enforced by __tests__/lib/catalog.test.js).

export const stencils = [
  // ==================== SERVICE VALUE CHAIN ====================
  {
    id: 'svc-engage',
    name: 'Engage',
    description: 'Understanding stakeholder needs and maintaining relationships',
    group: 'Service Value Chain',
    shape: 'rect',
    icon: '🤝',
    color: '#3b82f6',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
  {
    id: 'svc-plan',
    name: 'Plan',
    description: 'Ensuring shared understanding of vision and direction',
    group: 'Service Value Chain',
    shape: 'rect',
    icon: '📋',
    color: '#8b5cf6',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
  {
    id: 'svc-design',
    name: 'Design & Transition',
    description: 'Ensuring products meet stakeholder expectations',
    group: 'Service Value Chain',
    shape: 'rect',
    icon: '🎨',
    color: '#ec4899',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
  {
    id: 'svc-obtain',
    name: 'Obtain/Build',
    description: 'Ensuring service components are available',
    group: 'Service Value Chain',
    shape: 'rect',
    icon: '🔧',
    color: '#f59e0b',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
  {
    id: 'svc-deliver',
    name: 'Deliver & Support',
    description: 'Ensuring services are delivered and supported',
    group: 'Service Value Chain',
    shape: 'rect',
    icon: '🚀',
    color: '#22c55e',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
  {
    id: 'svc-improve',
    name: 'Improve',
    description: 'Ensuring continual improvement of services',
    group: 'Service Value Chain',
    shape: 'rect',
    icon: '📈',
    color: '#06b6d4',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },

  // ==================== SERVICE MANAGEMENT ====================
  {
    id: 'service',
    name: 'Service',
    description: 'IT Service that delivers value',
    group: 'Service Management',
    shape: 'rect',
    icon: '⚙️',
    color: '#3b82f6',
    defaultSize: { width: 160, height: 80 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'serviceType', label: 'Service Type', type: 'select', options: [
        { value: 'business', label: 'Business Service' },
        { value: 'technical', label: 'Technical Service' },
        { value: 'supporting', label: 'Supporting Service' },
      ]},
      { id: 'criticality', label: 'Criticality', type: 'select', options: [
        { value: 'critical', label: 'Critical' },
        { value: 'high', label: 'High' },
        { value: 'medium', label: 'Medium' },
        { value: 'low', label: 'Low' },
      ]},
      { id: 'slaTarget', label: 'SLA Target', type: 'text' },
    ],
  },
  {
    id: 'practice',
    name: 'Practice',
    description: 'ITIL Practice or capability',
    group: 'Service Management',
    shape: 'rect',
    icon: '📚',
    color: '#8b5cf6',
    defaultSize: { width: 160, height: 80 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'practiceType', label: 'Practice Type', type: 'select', options: [
        { value: 'general', label: 'General Management' },
        { value: 'service', label: 'Service Management' },
        { value: 'technical', label: 'Technical Management' },
      ]},
    ],
  },
  {
    id: 'process',
    name: 'Process',
    description: 'Documented process or procedure',
    group: 'Service Management',
    shape: 'rect',
    icon: '🔄',
    color: '#22c55e',
    defaultSize: { width: 160, height: 80 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'owner', label: 'Process Owner', type: 'text' },
      { id: 'status', label: 'Status', type: 'select', options: [
        { value: 'active', label: 'Active' },
        { value: 'draft', label: 'Draft' },
        { value: 'deprecated', label: 'Deprecated' },
      ]},
    ],
  },

  // ==================== INCIDENT & PROBLEM ====================
  {
    id: 'incident',
    name: 'Incident',
    description: 'Unplanned interruption to a service',
    group: 'Incident & Problem',
    shape: 'rect',
    icon: '⚠️',
    color: '#ef4444',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'priority', label: 'Priority', type: 'select', options: [
        { value: 'p1', label: 'P1 - Critical' },
        { value: 'p2', label: 'P2 - High' },
        { value: 'p3', label: 'P3 - Medium' },
        { value: 'p4', label: 'P4 - Low' },
      ]},
      { id: 'impact', label: 'Impact', type: 'select', options: [
        { value: 'high', label: 'High' },
        { value: 'medium', label: 'Medium' },
        { value: 'low', label: 'Low' },
      ]},
    ],
  },
  {
    id: 'problem',
    name: 'Problem',
    description: 'Root cause of one or more incidents',
    group: 'Incident & Problem',
    shape: 'rect',
    icon: '🔍',
    color: '#f59e0b',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'status', label: 'Status', type: 'select', options: [
        { value: 'open', label: 'Open' },
        { value: 'investigating', label: 'Investigating' },
        { value: 'known-error', label: 'Known Error' },
        { value: 'resolved', label: 'Resolved' },
      ]},
    ],
  },
  {
    id: 'known-error',
    name: 'Known Error',
    description: 'Problem with documented root cause and workaround',
    group: 'Incident & Problem',
    shape: 'rect',
    icon: '📋',
    color: '#6b7280',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'workaround', label: 'Workaround', type: 'textarea' },
    ],
  },

  // ==================== CHANGE MANAGEMENT ====================
  {
    id: 'change-request',
    name: 'Change Request',
    description: 'Request for change to the IT environment',
    group: 'Change Management',
    shape: 'rect',
    icon: '📝',
    color: '#3b82f6',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'changeType', label: 'Change Type', type: 'select', options: [
        { value: 'standard', label: 'Standard' },
        { value: 'normal', label: 'Normal' },
        { value: 'emergency', label: 'Emergency' },
      ]},
      { id: 'risk', label: 'Risk Level', type: 'select', options: [
        { value: 'high', label: 'High' },
        { value: 'medium', label: 'Medium' },
        { value: 'low', label: 'Low' },
      ]},
    ],
  },
  {
    id: 'release',
    name: 'Release',
    description: 'Collection of changes deployed together',
    group: 'Change Management',
    shape: 'rect',
    icon: '📦',
    color: '#22c55e',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'version', label: 'Version', type: 'text' },
      { id: 'releaseDate', label: 'Release Date', type: 'text' },
    ],
  },

  // ==================== CONFIGURATION ====================
  {
    id: 'ci',
    name: 'Configuration Item',
    description: 'Component that needs to be managed',
    group: 'Configuration',
    shape: 'rect',
    icon: '🖥️',
    color: '#8b5cf6',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'ciType', label: 'CI Type', type: 'select', options: [
        { value: 'hardware', label: 'Hardware' },
        { value: 'software', label: 'Software' },
        { value: 'network', label: 'Network' },
        { value: 'document', label: 'Document' },
        { value: 'service', label: 'Service' },
      ]},
      { id: 'status', label: 'Status', type: 'select', options: [
        { value: 'active', label: 'Active' },
        { value: 'planned', label: 'Planned' },
        { value: 'retired', label: 'Retired' },
      ]},
      { id: 'owner', label: 'Owner', type: 'text' },
    ],
  },
  {
    id: 'cmdb',
    name: 'CMDB',
    description: 'Configuration Management Database',
    group: 'Configuration',
    shape: 'rect',
    icon: '🗄️',
    color: '#06b6d4',
    defaultSize: { width: 200, height: 150 },
    ports: [],
    isContainer: true,
  },

  // ==================== STAKEHOLDERS ====================
  {
    id: 'stakeholder',
    name: 'Stakeholder',
    description: 'Person or organization with interest in the service',
    group: 'Stakeholders',
    shape: 'rect',
    icon: '👤',
    color: '#3b82f6',
    defaultSize: { width: 80, height: 100 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'role', label: 'Role', type: 'text' },
      { id: 'organization', label: 'Organization', type: 'text' },
    ],
  },
  {
    id: 'team',
    name: 'Team',
    description: 'Group responsible for service delivery',
    group: 'Stakeholders',
    shape: 'rect',
    icon: '👥',
    color: '#22c55e',
    defaultSize: { width: 160, height: 80 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'teamType', label: 'Team Type', type: 'select', options: [
        { value: 'support', label: 'Support Team' },
        { value: 'development', label: 'Development Team' },
        { value: 'operations', label: 'Operations Team' },
        { value: 'security', label: 'Security Team' },
      ]},
    ],
  },

  // ==================== ANNOTATIONS ====================
  {
    id: 'sla',
    name: 'SLA',
    description: 'Service Level Agreement',
    group: 'Annotations',
    shape: 'rect',
    icon: '📜',
    color: '#f59e0b',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'left', position: 'left' },
      { id: 'right', position: 'right' },
    ],
    isContainer: false,
    properties: [
      { id: 'target', label: 'Target', type: 'text', placeholder: '99.9%' },
      { id: 'metric', label: 'Metric', type: 'text', placeholder: 'Availability' },
    ],
  },
  {
    id: 'kpi',
    name: 'KPI',
    description: 'Key Performance Indicator',
    group: 'Annotations',
    shape: 'rect',
    icon: '📊',
    color: '#22c55e',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'left', position: 'left' },
      { id: 'right', position: 'right' },
    ],
    isContainer: false,
    properties: [
      { id: 'value', label: 'Value', type: 'text' },
      { id: 'target', label: 'Target', type: 'text' },
    ],
  },
];

export const connectionTypes = [
  {
    id: 'depends-on',
    name: 'Depends On',
    description: 'Dependency relationship',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#374151',
  },
  {
    id: 'supports',
    name: 'Supports',
    description: 'Supporting relationship',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#22c55e',
  },
  {
    id: 'triggers',
    name: 'Triggers',
    description: 'Triggering relationship',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#f59e0b',
  },
  {
    id: 'escalates-to',
    name: 'Escalates To',
    description: 'Escalation path',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#ef4444',
  },
  {
    id: 'relates-to',
    name: 'Relates To',
    description: 'General relationship',
    style: 'dotted',
    arrowStart: 'none',
    arrowEnd: 'none',
    color: '#6b7280',
  },
  {
    id: 'contains',
    name: 'Contains',
    description: 'Containment relationship',
    style: 'solid',
    arrowStart: 'diamond-filled',
    arrowEnd: 'none',
    color: '#374151',
  },
  {
    id: 'input-output',
    name: 'Input/Output',
    description: 'Data or value flow',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#3b82f6',
  },
];
