// Catalog data for the "process-flow" pack: plain data, no React. Shared by the pack (rendering) and the MCP server.
// Do not import UI code here (enforced by __tests__/lib/catalog.test.js).

export const stencils = [
  // ==================== GROUP 1: TASKS & EVENTS ====================
  {
    id: 'start-event',
    name: 'Start',
    description: 'Start event - beginning of the process',
    group: 'Tasks & Events',
    shape: 'circle',
    icon: '▶',
    color: '#22c55e',
    defaultSize: { width: 44, height: 44 },
    ports: [
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
    ],
    isContainer: false,
  },
  {
    id: 'end-event',
    name: 'End',
    description: 'End event - termination of the process',
    group: 'Tasks & Events',
    shape: 'circle',
    icon: '⬤',
    color: '#ef4444',
    defaultSize: { width: 44, height: 44 },
    ports: [
      { id: 'left', position: 'left' },
      { id: 'top', position: 'top' },
    ],
    isContainer: false,
  },
  {
    id: 'task',
    name: 'Task',
    description: 'A unit of work to be performed',
    group: 'Tasks & Events',
    shape: 'rect',
    icon: '☐',
    color: '#3b82f6',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'assignee', label: 'Assignee', type: 'text' },
      { id: 'duration', label: 'Duration', type: 'text' },
      { id: 'taskType', label: 'Task Type', type: 'select', options: [
        { value: 'manual', label: 'Manual' },
        { value: 'automated', label: 'Automated' },
        { value: 'user', label: 'User Task' },
        { value: 'service', label: 'Service Task' },
      ]},
    ],
  },
  {
    id: 'subprocess',
    name: 'Subprocess',
    description: 'A compound activity that references another process',
    group: 'Tasks & Events',
    shape: 'rect',
    icon: '⊞',
    color: '#8b5cf6',
    defaultSize: { width: 160, height: 80 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: true,
    properties: [
      { id: 'linkedProcess', label: 'Linked Process', type: 'text' },
      { id: 'collapsed', label: 'Collapsed', type: 'boolean' },
    ],
  },
  {
    id: 'intermediate-event',
    name: 'Intermediate',
    description: 'Intermediate event - something that happens during the process',
    group: 'Tasks & Events',
    shape: 'circle',
    icon: '◎',
    color: '#f59e0b',
    defaultSize: { width: 44, height: 44 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'eventType', label: 'Event Type', type: 'select', options: [
        { value: 'timer', label: 'Timer' },
        { value: 'message', label: 'Message' },
        { value: 'error', label: 'Error' },
        { value: 'signal', label: 'Signal' },
      ]},
    ],
  },

  // ==================== GROUP 2: FLOW CONTROL ====================
  {
    id: 'exclusive-gateway',
    name: 'Decision',
    description: 'Exclusive gateway - only one path can be taken (XOR)',
    group: 'Flow Control',
    shape: 'diamond',
    icon: '◇',
    color: '#f59e0b',
    defaultSize: { width: 110, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'condition', label: 'Condition', type: 'text' },
    ],
  },
  {
    id: 'parallel-gateway',
    name: 'Parallel',
    description: 'Parallel gateway - all paths are taken simultaneously (AND)',
    group: 'Flow Control',
    shape: 'diamond',
    icon: '+',
    color: '#22c55e',
    defaultSize: { width: 60, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
  {
    id: 'inclusive-gateway',
    name: 'Inclusive',
    description: 'Inclusive gateway - one or more paths can be taken (OR)',
    group: 'Flow Control',
    shape: 'diamond',
    icon: '○',
    color: '#8b5cf6',
    defaultSize: { width: 60, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
  {
    id: 'merge',
    name: 'Merge',
    description: 'Merge multiple paths back into one',
    group: 'Flow Control',
    shape: 'diamond',
    icon: '⋈',
    color: '#06b6d4',
    defaultSize: { width: 60, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },

  // ==================== GROUP 3: ORGANIZATION ====================
  {
    id: 'pool',
    name: 'Pool',
    description: 'A container for a single process',
    group: 'Organization',
    shape: 'rect',
    icon: '▭',
    color: '#374151',
    defaultSize: { width: 600, height: 300 },
    ports: [],
    isContainer: true,
    properties: [
      { id: 'participant', label: 'Participant', type: 'text' },
    ],
  },
  {
    id: 'lane',
    name: 'Lane',
    description: 'A sub-partition within a pool (role/department)',
    group: 'Organization',
    shape: 'rect',
    icon: '▬',
    color: '#e5e7eb',
    defaultSize: { width: 500, height: 150 },
    ports: [],
    isContainer: true,
    properties: [
      { id: 'role', label: 'Role/Department', type: 'text' },
    ],
  },
  {
    id: 'data-object',
    name: 'Document',
    description: 'Information/data that flows through the process',
    group: 'Organization',
    shape: 'rect',
    icon: '📄',
    color: '#6b7280',
    defaultSize: { width: 50, height: 65 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'dataType', label: 'Data Type', type: 'text' },
    ],
  },
  {
    id: 'data-store',
    name: 'Database',
    description: 'A place to store data persistently',
    group: 'Organization',
    shape: 'rect',
    icon: '🗄',
    color: '#6b7280',
    defaultSize: { width: 70, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'storeName', label: 'Store Name', type: 'text' },
    ],
  },
  {
    id: 'annotation',
    name: 'Note',
    description: 'Additional text annotation',
    group: 'Organization',
    shape: 'rect',
    icon: '📝',
    color: '#9ca3af',
    defaultSize: { width: 150, height: 60 },
    ports: [
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
];

export const connectionTypes = [
  {
    id: 'sequence-flow',
    name: 'Sequence Flow',
    description: 'Normal flow between activities',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#374151',
  },
  {
    id: 'conditional-flow',
    name: 'Conditional Flow',
    description: 'Flow with a condition',
    style: 'solid',
    arrowStart: 'diamond',
    arrowEnd: 'arrow',
    color: '#f59e0b',
  },
  {
    id: 'default-flow',
    name: 'Default Flow',
    description: 'Default path from a gateway',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#374151',
    marker: 'slash',
  },
  {
    id: 'message-flow',
    name: 'Message Flow',
    description: 'Communication between pools',
    style: 'dashed',
    arrowStart: 'circle',
    arrowEnd: 'arrow',
    color: '#3b82f6',
  },
  {
    id: 'association',
    name: 'Association',
    description: 'Association with data or annotations',
    style: 'dotted',
    arrowStart: 'none',
    arrowEnd: 'none',
    color: '#9ca3af',
  },
];
