// Catalog data for the "product-design" pack: plain data, no React. Shared by the pack (rendering) and the MCP server.
// Do not import UI code here (enforced by __tests__/lib/catalog.test.js).

export const stencils = [
  // Generic Cards
  {
    id: 'insight-card',
    name: 'Insight Card',
    description: 'Card for insights and observations',
    group: 'Cards',
    shape: 'sticky',
    icon: '💡',
    color: '#fef08a',
    defaultSize: { width: 160, height: 100 },
    ports: [],
    isContainer: false,
    properties: [
      { id: 'evidence', label: 'Evidence', type: 'text' },
      { id: 'confidence', label: 'Confidence', type: 'select', options: [
        { value: 'low', label: 'Low' },
        { value: 'medium', label: 'Medium' },
        { value: 'high', label: 'High' },
      ]},
      { id: 'source', label: 'Source', type: 'text' },
    ],
  },
  {
    id: 'action-card',
    name: 'Action Card',
    description: 'Card for actions and behaviors',
    group: 'Cards',
    shape: 'sticky',
    icon: '⚡',
    color: '#93c5fd',
    defaultSize: { width: 160, height: 100 },
    ports: [],
    isContainer: false,
  },
  {
    id: 'pain-point',
    name: 'Pain Point',
    description: 'Pain point or friction',
    group: 'Cards',
    shape: 'sticky',
    icon: '❌',
    color: '#fca5a5',
    defaultSize: { width: 160, height: 100 },
    ports: [],
    isContainer: false,
  },
  {
    id: 'opportunity-card',
    name: 'Opportunity',
    description: 'Opportunity or improvement idea',
    group: 'Cards',
    shape: 'sticky',
    icon: '✨',
    color: '#86efac',
    defaultSize: { width: 160, height: 100 },
    ports: [],
    isContainer: false,
  },
  {
    id: 'quote-card',
    name: 'Quote',
    description: 'Direct user quote',
    group: 'Cards',
    shape: 'sticky',
    icon: '"',
    color: '#e9d5ff',
    defaultSize: { width: 160, height: 100 },
    ports: [],
    isContainer: false,
    properties: [
      { id: 'speaker', label: 'Speaker', type: 'text' },
    ],
  },

  // OST Nodes
  {
    id: 'outcome-node',
    name: 'Outcome',
    description: 'Desired outcome (OST root)',
    group: 'OST',
    shape: 'rect',
    icon: '🎯',
    color: '#3b82f6',
    defaultSize: { width: 220, height: 80 },
    ports: ['bottom'],
    isContainer: false,
    properties: [
      { id: 'metric', label: 'Success Metric', type: 'text' },
      { id: 'timeHorizon', label: 'Time Horizon', type: 'text' },
    ],
  },
  {
    id: 'opportunity-node',
    name: 'Opportunity',
    description: 'Problem or unmet need (OST)',
    group: 'OST',
    shape: 'rect',
    icon: '🔍',
    color: '#8b5cf6',
    defaultSize: { width: 180, height: 70 },
    ports: ['top', 'bottom'],
    isContainer: false,
    properties: [
      { id: 'evidence', label: 'Evidence', type: 'text' },
      { id: 'impact', label: 'Impact', type: 'select', options: [
        { value: 'low', label: 'Low' },
        { value: 'medium', label: 'Medium' },
        { value: 'high', label: 'High' },
      ]},
    ],
  },
  {
    id: 'solution-node',
    name: 'Solution',
    description: 'Solution idea (OST)',
    group: 'OST',
    shape: 'rect',
    icon: '💡',
    color: '#10b981',
    defaultSize: { width: 160, height: 60 },
    ports: ['top', 'bottom'],
    isContainer: false,
    properties: [
      { id: 'assumptions', label: 'Assumptions', type: 'text' },
      { id: 'feasibility', label: 'Feasibility', type: 'text' },
    ],
  },
  {
    id: 'experiment-node',
    name: 'Experiment',
    description: 'Validation experiment (OST)',
    group: 'OST',
    shape: 'rect',
    icon: '🧪',
    color: '#f59e0b',
    defaultSize: { width: 150, height: 55 },
    ports: ['top'],
    isContainer: false,
    style: { borderStyle: 'dashed' },
    properties: [
      { id: 'hypothesis', label: 'Hypothesis', type: 'text' },
      { id: 'successSignal', label: 'Success Signal', type: 'text' },
    ],
  },

  // Zone Containers (for fixed layouts)
  {
    id: 'quadrant-zone',
    name: 'Quadrant Zone',
    description: 'Fixed zone for 2x2 layouts',
    group: 'Zones',
    shape: 'rect',
    icon: '▦',
    color: '#f3f4f6',
    defaultSize: { width: 400, height: 300 },
    ports: [],
    isContainer: true,
    isZone: true, // Special flag for constrained placement
    properties: [
      { id: 'zoneId', label: 'Zone ID', type: 'text' },
    ],
  },
  {
    id: 'lane-zone',
    name: 'Lane Zone',
    description: 'Horizontal lane for timeline layouts',
    group: 'Zones',
    shape: 'rect',
    icon: '═',
    color: '#f9fafb',
    defaultSize: { width: 800, height: 100 },
    ports: [],
    isContainer: true,
    isZone: true,
  },
  {
    id: 'phase-container',
    name: 'Phase',
    description: 'Phase container for journey maps',
    group: 'Zones',
    shape: 'rect',
    icon: '▭',
    color: '#e5e7eb',
    defaultSize: { width: 200, height: 500 },
    ports: [],
    isContainer: true,
    isZone: true,
  },
  {
    id: 'column-zone',
    name: 'Column Zone',
    description: 'Column for board layouts',
    group: 'Zones',
    shape: 'rect',
    icon: '▯',
    color: '#f3f4f6',
    defaultSize: { width: 220, height: 500 },
    ports: [],
    isContainer: true,
    isZone: true,
  },
  {
    id: 'section-zone',
    name: 'Section',
    description: 'Section for structured canvases',
    group: 'Zones',
    shape: 'rect',
    icon: '▭',
    color: '#fafafa',
    defaultSize: { width: 350, height: 180 },
    ports: [],
    isContainer: true,
    isZone: true,
  },

  // Persona Elements
  {
    id: 'persona-header',
    name: 'Persona Header',
    description: 'Persona profile header',
    group: 'Persona',
    shape: 'rect',
    icon: '👤',
    color: '#dbeafe',
    defaultSize: { width: 720, height: 120 },
    ports: [],
    isContainer: false,
    properties: [
      { id: 'role', label: 'Role', type: 'text' },
      { id: 'segment', label: 'Segment', type: 'text' },
    ],
  },

  // Journey Map Elements
  {
    id: 'touchpoint',
    name: 'Touchpoint',
    description: 'Customer touchpoint',
    group: 'Journey',
    shape: 'rect',
    icon: '📱',
    color: '#c4b5fd',
    defaultSize: { width: 140, height: 60 },
    ports: [],
    isContainer: false,
    properties: [
      { id: 'channel', label: 'Channel', type: 'text' },
    ],
  },
  {
    id: 'emotion-point',
    name: 'Emotion Point',
    description: 'Emotion indicator on journey',
    group: 'Journey',
    shape: 'circle',
    icon: '😊',
    color: '#fbbf24',
    defaultSize: { width: 40, height: 40 },
    ports: ['left', 'right'],
    isContainer: false,
    properties: [
      { id: 'score', label: 'Emotion Score (-2 to +2)', type: 'number' },
    ],
  },

  // RICE/Table Elements
  {
    id: 'scored-item',
    name: 'Scored Item',
    description: 'Item with RICE scoring',
    group: 'Scoring',
    shape: 'rect',
    icon: '📊',
    color: '#e0e7ff',
    defaultSize: { width: 180, height: 50 },
    ports: [],
    isContainer: false,
    properties: [
      { id: 'reach', label: 'Reach', type: 'number' },
      { id: 'impact', label: 'Impact (1-3)', type: 'number' },
      { id: 'confidence', label: 'Confidence (0-1)', type: 'number' },
      { id: 'effort', label: 'Effort', type: 'number' },
    ],
  },

  // Generic sticky note variants
  {
    id: 'yellow-card',
    name: 'Yellow Card',
    group: 'Colors',
    shape: 'sticky',
    icon: '📋',
    color: '#fef08a',
    defaultSize: { width: 140, height: 100 },
    ports: [],
    isContainer: false,
  },
  {
    id: 'blue-card',
    name: 'Blue Card',
    group: 'Colors',
    shape: 'sticky',
    icon: '📋',
    color: '#93c5fd',
    defaultSize: { width: 140, height: 100 },
    ports: [],
    isContainer: false,
  },
  {
    id: 'green-card',
    name: 'Green Card',
    group: 'Colors',
    shape: 'sticky',
    icon: '📋',
    color: '#86efac',
    defaultSize: { width: 140, height: 100 },
    ports: [],
    isContainer: false,
  },
  {
    id: 'pink-card',
    name: 'Pink Card',
    group: 'Colors',
    shape: 'sticky',
    icon: '📋',
    color: '#f9a8d4',
    defaultSize: { width: 140, height: 100 },
    ports: [],
    isContainer: false,
  },
  {
    id: 'orange-card',
    name: 'Orange Card',
    group: 'Colors',
    shape: 'sticky',
    icon: '📋',
    color: '#fdba74',
    defaultSize: { width: 140, height: 100 },
    ports: [],
    isContainer: false,
  },
  {
    id: 'purple-card',
    name: 'Purple Card',
    group: 'Colors',
    shape: 'sticky',
    icon: '📋',
    color: '#c4b5fd',
    defaultSize: { width: 140, height: 100 },
    ports: [],
    isContainer: false,
  },
];

export const connectionTypes = [
  {
    id: 'hierarchy',
    name: 'Hierarchy',
    description: 'Parent-child relationship',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#6b7280',
  },
  {
    id: 'emotion-curve',
    name: 'Emotion Curve',
    description: 'Connects emotion points in journey',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'none',
    color: '#f59e0b',
    strokeWidth: 2,
  },
  {
    id: 'relationship',
    name: 'Relationship',
    description: 'General relationship',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'none',
    color: '#9ca3af',
  },
  {
    id: 'flow',
    name: 'Flow',
    description: 'Flow between phases',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#3b82f6',
  },
];
