// Catalog data for the "togaf" pack: plain data, no React. Shared by the pack (rendering) and the MCP server.
// Do not import UI code here (enforced by __tests__/lib/catalog.test.js).

export const stencils = [
  // ============ BUSINESS LAYER ============
  {
    id: 'business-actor',
    name: 'Business Actor',
    description: 'A business entity that is capable of performing behavior',
    group: 'Business',
    shape: 'rect',
    icon: '👤',
    color: '#fbbf24',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    properties: [
      { id: 'externalId', label: 'External ID', type: 'text' },
      { id: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    id: 'business-role',
    name: 'Business Role',
    description: 'The responsibility for performing specific behavior',
    group: 'Business',
    shape: 'rect',
    icon: '🎭',
    color: '#fbbf24',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'business-process',
    name: 'Business Process',
    description: 'A sequence of business behaviors',
    group: 'Business',
    shape: 'rect',
    icon: '⚙️',
    color: '#fbbf24',
    defaultSize: { width: 140, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    properties: [
      { id: 'processId', label: 'Process ID', type: 'text' },
      { id: 'owner', label: 'Process Owner', type: 'text' },
    ],
  },
  {
    id: 'business-function',
    name: 'Business Function',
    description: 'A collection of business behavior',
    group: 'Business',
    shape: 'rect',
    icon: '📦',
    color: '#fbbf24',
    defaultSize: { width: 140, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'business-service',
    name: 'Business Service',
    description: 'An explicitly defined exposed business behavior',
    group: 'Business',
    shape: 'rect',
    icon: '🔶',
    color: '#fbbf24',
    defaultSize: { width: 140, height: 50 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'business-object',
    name: 'Business Object',
    description: 'A concept used within a particular business domain',
    group: 'Business',
    shape: 'rect',
    icon: '📋',
    color: '#fbbf24',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'product',
    name: 'Product',
    description: 'A coherent collection of services and/or objects',
    group: 'Business',
    shape: 'rect',
    icon: '🎁',
    color: '#fbbf24',
    defaultSize: { width: 140, height: 80 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: true,
  },
  {
    id: 'contract',
    name: 'Contract',
    description: 'A formal agreement between parties',
    group: 'Business',
    shape: 'rect',
    icon: '📜',
    color: '#fbbf24',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },

  // ============ APPLICATION LAYER ============
  {
    id: 'application-component',
    name: 'Application Component',
    description: 'An encapsulation of application functionality',
    group: 'Application',
    shape: 'rect',
    icon: '💻',
    color: '#60a5fa',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    properties: [
      { id: 'version', label: 'Version', type: 'text' },
      { id: 'vendor', label: 'Vendor', type: 'text' },
      { id: 'technology', label: 'Technology', type: 'text' },
    ],
  },
  {
    id: 'application-service',
    name: 'Application Service',
    description: 'An explicitly defined exposed application behavior',
    group: 'Application',
    shape: 'rect',
    icon: '🔷',
    color: '#60a5fa',
    defaultSize: { width: 140, height: 50 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'application-interface',
    name: 'Application Interface',
    description: 'A point of access for application services',
    group: 'Application',
    shape: 'rect',
    icon: '🔌',
    color: '#60a5fa',
    defaultSize: { width: 100, height: 50 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    properties: [
      { id: 'protocol', label: 'Protocol', type: 'text' },
      { id: 'apiVersion', label: 'API Version', type: 'text' },
    ],
  },
  {
    id: 'application-function',
    name: 'Application Function',
    description: 'Automated behavior that an application can perform',
    group: 'Application',
    shape: 'rect',
    icon: '⚡',
    color: '#60a5fa',
    defaultSize: { width: 140, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'data-object',
    name: 'Data Object',
    description: 'Data structured for automated processing',
    group: 'Application',
    shape: 'rect',
    icon: '🗃️',
    color: '#60a5fa',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },

  // ============ TECHNOLOGY LAYER ============
  {
    id: 'node',
    name: 'Node',
    description: 'A computational resource upon which artifacts may be deployed',
    group: 'Technology',
    shape: 'rect',
    icon: '🖥️',
    color: '#34d399',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: true,
    properties: [
      { id: 'hostname', label: 'Hostname', type: 'text' },
      { id: 'os', label: 'Operating System', type: 'text' },
    ],
  },
  {
    id: 'device',
    name: 'Device',
    description: 'A physical IT resource upon which artifacts may be deployed',
    group: 'Technology',
    shape: 'rect',
    icon: '📱',
    color: '#34d399',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    properties: [
      { id: 'deviceType', label: 'Device Type', type: 'text' },
      { id: 'manufacturer', label: 'Manufacturer', type: 'text' },
    ],
  },
  {
    id: 'system-software',
    name: 'System Software',
    description: 'Software that provides or contributes to an environment',
    group: 'Technology',
    shape: 'rect',
    icon: '⚙️',
    color: '#34d399',
    defaultSize: { width: 140, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    properties: [
      { id: 'version', label: 'Version', type: 'text' },
    ],
  },
  {
    id: 'technology-service',
    name: 'Technology Service',
    description: 'An explicitly defined technology capability',
    group: 'Technology',
    shape: 'rect',
    icon: '🔹',
    color: '#34d399',
    defaultSize: { width: 140, height: 50 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'artifact',
    name: 'Artifact',
    description: 'A piece of data used or produced in a software development process',
    group: 'Technology',
    shape: 'rect',
    icon: '📄',
    color: '#34d399',
    defaultSize: { width: 100, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'communication-network',
    name: 'Communication Network',
    description: 'A set of structures connecting nodes',
    group: 'Technology',
    shape: 'rect',
    icon: '🌐',
    color: '#34d399',
    defaultSize: { width: 160, height: 40 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    properties: [
      { id: 'networkType', label: 'Network Type', type: 'text' },
      { id: 'bandwidth', label: 'Bandwidth', type: 'text' },
    ],
  },

  // ============ MOTIVATION LAYER ============
  {
    id: 'stakeholder',
    name: 'Stakeholder',
    description: 'The role of an individual, team, or organization',
    group: 'Motivation',
    shape: 'rect',
    icon: '👥',
    color: '#c084fc',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'driver',
    name: 'Driver',
    description: 'An external or internal condition that motivates change',
    group: 'Motivation',
    shape: 'rect',
    icon: '🎯',
    color: '#c084fc',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'assessment',
    name: 'Assessment',
    description: 'The result of an analysis of the state of affairs',
    group: 'Motivation',
    shape: 'rect',
    icon: '📊',
    color: '#c084fc',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'goal',
    name: 'Goal',
    description: 'A high-level statement of intent or direction',
    group: 'Motivation',
    shape: 'rect',
    icon: '🏆',
    color: '#c084fc',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    properties: [
      { id: 'priority', label: 'Priority', type: 'select', options: [
        { value: 'high', label: 'High' },
        { value: 'medium', label: 'Medium' },
        { value: 'low', label: 'Low' },
      ]},
    ],
  },
  {
    id: 'outcome',
    name: 'Outcome',
    description: 'An end result that has been achieved',
    group: 'Motivation',
    shape: 'rect',
    icon: '✅',
    color: '#c084fc',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'principle',
    name: 'Principle',
    description: 'A qualitative statement of intent',
    group: 'Motivation',
    shape: 'rect',
    icon: '📐',
    color: '#c084fc',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'requirement',
    name: 'Requirement',
    description: 'A statement of need that must be met',
    group: 'Motivation',
    shape: 'rect',
    icon: '📝',
    color: '#c084fc',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    properties: [
      { id: 'type', label: 'Type', type: 'select', options: [
        { value: 'functional', label: 'Functional' },
        { value: 'non-functional', label: 'Non-Functional' },
        { value: 'constraint', label: 'Constraint' },
      ]},
    ],
  },
  {
    id: 'constraint',
    name: 'Constraint',
    description: 'An external factor that limits the realization of goals',
    group: 'Motivation',
    shape: 'rect',
    icon: '⛔',
    color: '#c084fc',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },

  // ============ STRATEGY LAYER ============
  {
    id: 'resource',
    name: 'Resource',
    description: 'An asset owned or controlled by an individual or organization',
    group: 'Strategy',
    shape: 'rect',
    icon: '💎',
    color: '#f472b6',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'capability',
    name: 'Capability',
    description: 'An ability that an active structure element possesses',
    group: 'Strategy',
    shape: 'rect',
    icon: '💪',
    color: '#f472b6',
    defaultSize: { width: 140, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    properties: [
      { id: 'maturity', label: 'Maturity Level', type: 'select', options: [
        { value: '1', label: 'Initial' },
        { value: '2', label: 'Managed' },
        { value: '3', label: 'Defined' },
        { value: '4', label: 'Quantitatively Managed' },
        { value: '5', label: 'Optimizing' },
      ]},
    ],
  },
  {
    id: 'value-stream',
    name: 'Value Stream',
    description: 'A sequence of activities that create a result for a customer',
    group: 'Strategy',
    shape: 'rect',
    icon: '➡️',
    color: '#f472b6',
    defaultSize: { width: 160, height: 50 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'course-of-action',
    name: 'Course of Action',
    description: 'An approach or plan for configuring capabilities',
    group: 'Strategy',
    shape: 'rect',
    icon: '🗺️',
    color: '#f472b6',
    defaultSize: { width: 140, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },

  // ============ IMPLEMENTATION LAYER ============
  {
    id: 'work-package',
    name: 'Work Package',
    description: 'A series of actions to achieve a specific result',
    group: 'Implementation',
    shape: 'rect',
    icon: '📦',
    color: '#fb923c',
    defaultSize: { width: 140, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    properties: [
      { id: 'status', label: 'Status', type: 'select', options: [
        { value: 'planned', label: 'Planned' },
        { value: 'in-progress', label: 'In Progress' },
        { value: 'completed', label: 'Completed' },
      ]},
    ],
  },
  {
    id: 'deliverable',
    name: 'Deliverable',
    description: 'A precisely-defined outcome of a work package',
    group: 'Implementation',
    shape: 'rect',
    icon: '📋',
    color: '#fb923c',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },
  {
    id: 'plateau',
    name: 'Plateau',
    description: 'A relatively stable state of the architecture',
    group: 'Implementation',
    shape: 'rect',
    icon: '🏔️',
    color: '#fb923c',
    defaultSize: { width: 200, height: 100 },
    ports: [],
    isContainer: true,
    properties: [
      { id: 'targetDate', label: 'Target Date', type: 'text' },
    ],
  },
  {
    id: 'gap',
    name: 'Gap',
    description: 'A statement of difference between two plateaus',
    group: 'Implementation',
    shape: 'rect',
    icon: '⚠️',
    color: '#fb923c',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
  },

  // ============ GROUPING ============
  {
    id: 'grouping',
    name: 'Grouping',
    description: 'A grouping of elements',
    group: 'Composite',
    shape: 'rect',
    icon: '▢',
    color: '#94a3b8',
    defaultSize: { width: 250, height: 180 },
    ports: [],
    isContainer: true,
  },
  {
    id: 'location',
    name: 'Location',
    description: 'A place or position',
    group: 'Composite',
    shape: 'rect',
    icon: '📍',
    color: '#94a3b8',
    defaultSize: { width: 200, height: 150 },
    ports: [],
    isContainer: true,
    properties: [
      { id: 'address', label: 'Address', type: 'text' },
    ],
  },
];

export const connectionTypes = [
  // Structural relationships
  {
    id: 'composition',
    name: 'Composition',
    description: 'Indicates that an element consists of other elements',
    style: 'solid',
    arrowStart: 'diamond-filled',
    arrowEnd: 'none',
    color: '#374151',
  },
  {
    id: 'aggregation',
    name: 'Aggregation',
    description: 'Indicates that an element combines other elements',
    style: 'solid',
    arrowStart: 'diamond-empty',
    arrowEnd: 'none',
    color: '#374151',
  },
  {
    id: 'assignment',
    name: 'Assignment',
    description: 'Links units of behavior with active elements',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'filled-circle',
    color: '#374151',
  },
  {
    id: 'realization',
    name: 'Realization',
    description: 'Indicates that an entity realizes another entity',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'triangle-empty',
    color: '#374151',
  },
  // Dependency relationships
  {
    id: 'serving',
    name: 'Serving (Used By)',
    description: 'A service is provided to another element',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#374151',
  },
  {
    id: 'access',
    name: 'Access',
    description: 'The ability of behavior to observe or act upon data',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#6b7280',
  },
  {
    id: 'influence',
    name: 'Influence',
    description: 'An element affects implementation of a motivation element',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#9ca3af',
  },
  // Dynamic relationships
  {
    id: 'triggering',
    name: 'Triggering',
    description: 'A temporal or causal relationship',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#374151',
  },
  {
    id: 'flow',
    name: 'Flow',
    description: 'Transfer from one element to another',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#374151',
  },
  // Other relationships
  {
    id: 'specialization',
    name: 'Specialization',
    description: 'An element is a specialization of another element',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'triangle-empty',
    color: '#374151',
  },
  {
    id: 'association',
    name: 'Association',
    description: 'A relationship not covered by other relationships',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'none',
    color: '#6b7280',
  },
];
