// Catalog data for the "uml-class" pack: plain data, no React. Shared by the pack (rendering) and the MCP server.
// Do not import UI code here (enforced by __tests__/lib/catalog.test.js).

export const stencils = [
  // ==================== CLASS DIAGRAM ====================
  // Classes
  {
    id: 'class',
    name: 'Class',
    description: 'UML Class with name, attributes, and methods',
    group: 'Class Diagram',
    shape: 'rect',
    icon: '☐',
    color: '#3b82f6',
    defaultSize: { width: 180, height: 120 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    compartments: ['name', 'attributes', 'methods'],
    properties: [
      { id: 'stereotype', label: 'Stereotype', type: 'text', placeholder: 'e.g., entity, controller' },
      { id: 'isAbstract', label: 'Abstract', type: 'boolean' },
      { id: 'attributes', label: 'Attributes', type: 'list', placeholder: '+ name: String' },
      { id: 'methods', label: 'Methods', type: 'list', placeholder: '+ getName(): String' },
      { id: 'visibility', label: 'Default Visibility', type: 'select', options: [
        { value: 'public', label: 'Public (+)' },
        { value: 'private', label: 'Private (-)' },
        { value: 'protected', label: 'Protected (#)' },
        { value: 'package', label: 'Package (~)' },
      ]},
    ],
  },
  {
    id: 'abstract-class',
    name: 'Abstract Class',
    description: 'Abstract class (cannot be instantiated)',
    group: 'Class Diagram',
    shape: 'rect',
    icon: '☐',
    color: '#8b5cf6',
    defaultSize: { width: 180, height: 120 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    compartments: ['name', 'attributes', 'methods'],
    properties: [
      { id: 'stereotype', label: 'Stereotype', type: 'text' },
      { id: 'attributes', label: 'Attributes', type: 'list' },
      { id: 'methods', label: 'Methods', type: 'list' },
    ],
  },
  {
    id: 'interface',
    name: 'Interface',
    description: 'UML Interface',
    group: 'Class Diagram',
    shape: 'rect',
    icon: '○',
    color: '#22c55e',
    defaultSize: { width: 160, height: 100 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    compartments: ['name', 'methods'],
    properties: [
      { id: 'methods', label: 'Methods', type: 'list' },
    ],
  },
  {
    id: 'enum',
    name: 'Enumeration',
    description: 'UML Enumeration',
    group: 'Class Diagram',
    shape: 'rect',
    icon: '≡',
    color: '#f59e0b',
    defaultSize: { width: 140, height: 100 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    compartments: ['name', 'values'],
    properties: [
      { id: 'values', label: 'Values', type: 'list', placeholder: 'VALUE1, VALUE2' },
    ],
  },

  // Packages
  {
    id: 'package',
    name: 'Package',
    description: 'UML Package for organizing classes',
    group: 'Class Diagram',
    shape: 'rect',
    icon: '📦',
    color: '#64748b',
    defaultSize: { width: 250, height: 200 },
    ports: [],
    isContainer: true,
    properties: [
      { id: 'packagePath', label: 'Package Path', type: 'text', placeholder: 'com.example.models' },
    ],
  },
  {
    id: 'data-type',
    name: 'Data Type',
    description: 'Primitive or custom data type',
    group: 'Class Diagram',
    shape: 'rect',
    icon: 'T',
    color: '#06b6d4',
    defaultSize: { width: 120, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'baseType', label: 'Base Type', type: 'text' },
    ],
  },

  // ==================== USE CASE DIAGRAM ====================
  {
    id: 'actor',
    name: 'Actor',
    description: 'Person or system that interacts with the system',
    group: 'Use Case Diagram',
    shape: 'rect',
    icon: '🧑',
    color: '#3b82f6',
    defaultSize: { width: 60, height: 100 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'actorType', label: 'Actor Type', type: 'select', options: [
        { value: 'person', label: 'Person' },
        { value: 'system', label: 'External System' },
        { value: 'time', label: 'Time/Scheduler' },
      ]},
    ],
  },
  {
    id: 'use-case',
    name: 'Use Case',
    description: 'A specific functionality the system provides',
    group: 'Use Case Diagram',
    shape: 'ellipse',
    icon: '◯',
    color: '#22c55e',
    defaultSize: { width: 140, height: 70 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'preconditions', label: 'Preconditions', type: 'textarea' },
      { id: 'postconditions', label: 'Postconditions', type: 'textarea' },
      { id: 'mainFlow', label: 'Main Flow', type: 'textarea' },
    ],
  },
  {
    id: 'system-boundary',
    name: 'System Boundary',
    description: 'Container representing the system scope',
    group: 'Use Case Diagram',
    shape: 'rect',
    icon: '▢',
    color: '#64748b',
    defaultSize: { width: 400, height: 300 },
    ports: [],
    isContainer: true,
    properties: [
      { id: 'systemName', label: 'System Name', type: 'text' },
    ],
  },

  // ==================== ACTIVITY DIAGRAM ====================
  {
    id: 'initial-node',
    name: 'Initial Node',
    description: 'Starting point of the activity',
    group: 'Activity Diagram',
    shape: 'circle',
    icon: '●',
    color: '#1f2937',
    defaultSize: { width: 30, height: 30 },
    ports: [
      { id: 'bottom', position: 'bottom' },
      { id: 'right', position: 'right' },
    ],
    isContainer: false,
  },
  {
    id: 'final-node',
    name: 'Final Node',
    description: 'End point of the activity',
    group: 'Activity Diagram',
    shape: 'circle',
    icon: '◉',
    color: '#1f2937',
    defaultSize: { width: 30, height: 30 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
  {
    id: 'flow-final',
    name: 'Flow Final',
    description: 'End point of a flow (not entire activity)',
    group: 'Activity Diagram',
    shape: 'circle',
    icon: '⊗',
    color: '#6b7280',
    defaultSize: { width: 30, height: 30 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
  {
    id: 'action',
    name: 'Action',
    description: 'A single step in the activity',
    group: 'Activity Diagram',
    shape: 'rect',
    icon: '▭',
    color: '#3b82f6',
    defaultSize: { width: 140, height: 50 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'actionType', label: 'Action Type', type: 'select', options: [
        { value: 'call', label: 'Call Action' },
        { value: 'send', label: 'Send Signal' },
        { value: 'accept', label: 'Accept Event' },
        { value: 'time', label: 'Time Event' },
      ]},
    ],
  },
  {
    id: 'decision',
    name: 'Decision/Merge',
    description: 'Branch or merge point in the flow',
    group: 'Activity Diagram',
    shape: 'diamond',
    icon: '◇',
    color: '#f59e0b',
    defaultSize: { width: 50, height: 50 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'condition', label: 'Condition', type: 'text' },
    ],
  },
  {
    id: 'fork-join',
    name: 'Fork/Join',
    description: 'Parallel execution bar',
    group: 'Activity Diagram',
    shape: 'rect',
    icon: '▬',
    color: '#1f2937',
    defaultSize: { width: 150, height: 8 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'bottom', position: 'bottom' },
    ],
    isContainer: false,
    properties: [
      { id: 'orientation', label: 'Orientation', type: 'select', options: [
        { value: 'horizontal', label: 'Horizontal' },
        { value: 'vertical', label: 'Vertical' },
      ]},
    ],
  },
  {
    id: 'swimlane',
    name: 'Swimlane',
    description: 'Partition for organizing activities by role',
    group: 'Activity Diagram',
    shape: 'rect',
    icon: '▯',
    color: '#e5e7eb',
    defaultSize: { width: 200, height: 400 },
    ports: [],
    isContainer: true,
    properties: [
      { id: 'responsible', label: 'Responsible', type: 'text' },
    ],
  },
  {
    id: 'object-node',
    name: 'Object Node',
    description: 'Data or object flowing through the activity',
    group: 'Activity Diagram',
    shape: 'rect',
    icon: '▭',
    color: '#8b5cf6',
    defaultSize: { width: 100, height: 50 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'objectState', label: 'State', type: 'text' },
    ],
  },

  // ==================== STATE MACHINE DIAGRAM ====================
  {
    id: 'initial-state',
    name: 'Initial State',
    description: 'Starting point of the state machine',
    group: 'State Machine',
    shape: 'circle',
    icon: '●',
    color: '#1f2937',
    defaultSize: { width: 30, height: 30 },
    ports: [
      { id: 'bottom', position: 'bottom' },
      { id: 'right', position: 'right' },
    ],
    isContainer: false,
  },
  {
    id: 'final-state',
    name: 'Final State',
    description: 'End point of the state machine',
    group: 'State Machine',
    shape: 'circle',
    icon: '◉',
    color: '#1f2937',
    defaultSize: { width: 30, height: 30 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
  {
    id: 'state',
    name: 'State',
    description: 'A state in the state machine',
    group: 'State Machine',
    shape: 'rect',
    icon: '▢',
    color: '#22c55e',
    defaultSize: { width: 140, height: 80 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'entry', label: 'Entry Action', type: 'text', placeholder: 'entry / action' },
      { id: 'exit', label: 'Exit Action', type: 'text', placeholder: 'exit / action' },
      { id: 'doActivity', label: 'Do Activity', type: 'text', placeholder: 'do / activity' },
      { id: 'internalTransitions', label: 'Internal Transitions', type: 'list' },
    ],
  },
  {
    id: 'composite-state',
    name: 'Composite State',
    description: 'State containing sub-states',
    group: 'State Machine',
    shape: 'rect',
    icon: '▣',
    color: '#3b82f6',
    defaultSize: { width: 300, height: 200 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: true,
    properties: [
      { id: 'entry', label: 'Entry Action', type: 'text' },
      { id: 'exit', label: 'Exit Action', type: 'text' },
    ],
  },
  {
    id: 'choice',
    name: 'Choice',
    description: 'Dynamic conditional branch',
    group: 'State Machine',
    shape: 'diamond',
    icon: '◇',
    color: '#f59e0b',
    defaultSize: { width: 40, height: 40 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
  {
    id: 'history',
    name: 'History',
    description: 'Shallow or deep history pseudo-state',
    group: 'State Machine',
    shape: 'circle',
    icon: 'H',
    color: '#6b7280',
    defaultSize: { width: 30, height: 30 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'right', position: 'right' },
      { id: 'bottom', position: 'bottom' },
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
    properties: [
      { id: 'historyType', label: 'History Type', type: 'select', options: [
        { value: 'shallow', label: 'Shallow (H)' },
        { value: 'deep', label: 'Deep (H*)' },
      ]},
    ],
  },

  // ==================== SEQUENCE DIAGRAM ====================
  {
    id: 'lifeline',
    name: 'Lifeline',
    description: 'Participant in a sequence diagram',
    group: 'Sequence Diagram',
    shape: 'rect',
    icon: '│',
    color: '#3b82f6',
    defaultSize: { width: 100, height: 300 },
    ports: [
      { id: 'left', position: 'left' },
      { id: 'right', position: 'right' },
    ],
    isContainer: false,
    properties: [
      { id: 'objectName', label: 'Object Name', type: 'text' },
      { id: 'className', label: 'Class Name', type: 'text' },
    ],
  },
  {
    id: 'activation',
    name: 'Activation',
    description: 'Period when lifeline is active',
    group: 'Sequence Diagram',
    shape: 'rect',
    icon: '▮',
    color: '#22c55e',
    defaultSize: { width: 16, height: 60 },
    ports: [
      { id: 'top', position: 'top' },
      { id: 'bottom', position: 'bottom' },
    ],
    isContainer: false,
  },
  {
    id: 'combined-fragment',
    name: 'Combined Fragment',
    description: 'Alt, loop, opt, or other fragment',
    group: 'Sequence Diagram',
    shape: 'rect',
    icon: '▢',
    color: '#64748b',
    defaultSize: { width: 300, height: 150 },
    ports: [],
    isContainer: true,
    properties: [
      { id: 'fragmentType', label: 'Fragment Type', type: 'select', options: [
        { value: 'alt', label: 'alt (alternative)' },
        { value: 'opt', label: 'opt (optional)' },
        { value: 'loop', label: 'loop' },
        { value: 'break', label: 'break' },
        { value: 'par', label: 'par (parallel)' },
        { value: 'critical', label: 'critical' },
        { value: 'ref', label: 'ref (reference)' },
      ]},
      { id: 'guard', label: 'Guard Condition', type: 'text', placeholder: '[condition]' },
    ],
  },

  // ==================== COMMON/ANNOTATIONS ====================
  {
    id: 'note',
    name: 'Note',
    description: 'UML Note/Comment',
    group: 'Annotations',
    shape: 'rect',
    icon: '📝',
    color: '#fef3c7',
    defaultSize: { width: 150, height: 80 },
    ports: [
      { id: 'left', position: 'left' },
    ],
    isContainer: false,
  },
  {
    id: 'constraint',
    name: 'Constraint',
    description: 'OCL or other constraint',
    group: 'Annotations',
    shape: 'rect',
    icon: '{',
    color: '#e5e7eb',
    defaultSize: { width: 140, height: 50 },
    ports: [],
    isContainer: false,
    properties: [
      { id: 'constraintBody', label: 'Constraint', type: 'textarea', placeholder: '{constraint expression}' },
    ],
  },
];

export const connectionTypes = [
  // ==================== CLASS DIAGRAM ====================
  {
    id: 'association',
    name: 'Association',
    description: 'Simple association between classes',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'none',
    color: '#374151',
    group: 'Class Diagram',
  },
  {
    id: 'directed-association',
    name: 'Directed Association',
    description: 'Navigable association',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#374151',
    group: 'Class Diagram',
  },
  {
    id: 'aggregation',
    name: 'Aggregation',
    description: 'Whole-part relationship (weak)',
    style: 'solid',
    arrowStart: 'diamond-empty',
    arrowEnd: 'none',
    color: '#374151',
    group: 'Class Diagram',
  },
  {
    id: 'composition',
    name: 'Composition',
    description: 'Whole-part relationship (strong)',
    style: 'solid',
    arrowStart: 'diamond-filled',
    arrowEnd: 'none',
    color: '#374151',
    group: 'Class Diagram',
  },
  {
    id: 'inheritance',
    name: 'Inheritance',
    description: 'Generalization (extends)',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'triangle-empty',
    color: '#374151',
    group: 'Class Diagram',
  },
  {
    id: 'realization',
    name: 'Realization',
    description: 'Interface implementation',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'triangle-empty',
    color: '#374151',
    group: 'Class Diagram',
  },
  {
    id: 'dependency',
    name: 'Dependency',
    description: 'Dependency relationship',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#6b7280',
    group: 'Class Diagram',
  },

  // ==================== USE CASE DIAGRAM ====================
  {
    id: 'uc-association',
    name: 'Association',
    description: 'Actor-UseCase association',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'none',
    color: '#374151',
    group: 'Use Case Diagram',
  },
  {
    id: 'include',
    name: 'Include',
    description: 'Include relationship (<<include>>)',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#374151',
    group: 'Use Case Diagram',
    labelTemplate: '<<include>>',
  },
  {
    id: 'extend',
    name: 'Extend',
    description: 'Extend relationship (<<extend>>)',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#374151',
    group: 'Use Case Diagram',
    labelTemplate: '<<extend>>',
  },
  {
    id: 'generalization',
    name: 'Generalization',
    description: 'Actor or UseCase generalization',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'triangle-empty',
    color: '#374151',
    group: 'Use Case Diagram',
  },

  // ==================== ACTIVITY DIAGRAM ====================
  {
    id: 'control-flow',
    name: 'Control Flow',
    description: 'Flow of control between actions',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#374151',
    group: 'Activity Diagram',
  },
  {
    id: 'object-flow',
    name: 'Object Flow',
    description: 'Flow of data/objects between nodes',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#8b5cf6',
    group: 'Activity Diagram',
  },

  // ==================== STATE MACHINE ====================
  {
    id: 'transition',
    name: 'Transition',
    description: 'State transition',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#374151',
    group: 'State Machine',
  },

  // ==================== SEQUENCE DIAGRAM ====================
  {
    id: 'sync-message',
    name: 'Synchronous Message',
    description: 'Synchronous call (filled arrow)',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'triangle-filled',
    color: '#374151',
    group: 'Sequence Diagram',
  },
  {
    id: 'async-message',
    name: 'Asynchronous Message',
    description: 'Asynchronous call (open arrow)',
    style: 'solid',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#374151',
    group: 'Sequence Diagram',
  },
  {
    id: 'return-message',
    name: 'Return Message',
    description: 'Return from a call',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#6b7280',
    group: 'Sequence Diagram',
  },
  {
    id: 'create-message',
    name: 'Create Message',
    description: 'Object creation',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#22c55e',
    group: 'Sequence Diagram',
    labelTemplate: '<<create>>',
  },
  {
    id: 'destroy-message',
    name: 'Destroy Message',
    description: 'Object destruction',
    style: 'dashed',
    arrowStart: 'none',
    arrowEnd: 'arrow',
    color: '#ef4444',
    group: 'Sequence Diagram',
    labelTemplate: '<<destroy>>',
  },

  // ==================== COMMON ====================
  {
    id: 'note-link',
    name: 'Note Link',
    description: 'Link to note/comment',
    style: 'dotted',
    arrowStart: 'none',
    arrowEnd: 'none',
    color: '#9ca3af',
    group: 'Annotations',
  },
];
